name: orb-scanner-api-realtime
services:
- name: web
  source_dir: /
  github:
    repo: Jrooker06/orb-scanner-api-Realtime
    branch: main
  run_command: gunicorn --bind 0.0.0.0:$PORT api_server:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  build_command: pip install -r requirements.txt
  envs:
  - key: POLYGON_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${POLYGON_API_KEY}
  - key: FINNHUB_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${FINNHUB_API_KEY}
  - key: VALID_LICENSE_KEYS
    scope: RUN_AND_BUILD_TIME
    value: "test-license-123,prod-license-456"
  - key: PORT
    scope: RUN_TIME
    value: "8080" 